### ISSUE TITLE
bug on dungeons and tower

### ISSUE THREAD

**Issue by lucalattanzio97** [TheXFactor117/Loot-Slash-Conquer-Pre1.14#31]
#not long after starting a new world, in a tower or dungeon, i cant play anymore... mobs dont move anymore, i cant open chests or anvil or anything else, cant attack mobs, cant eat and so on... also i cant close the world or minecraft either... i have to force it to close

i use these mods:
tinkers construct, jei, nei, terraqueous, etra utiities 2, hardcore ore and xaeros minimap.

**Comment by DuNamarSundavar** [comment]
If you're still within about 1K blocks of spawn, you should be fine unless mod compatibility is causing an issue. Otherwise, if you're out at the point where enemies and the Area Level are around level 30, it's an issue with multi-enchanted weapons and armor, with some properties of the weapons LSC adds, and with Minecraft's health cap of 1024.0 interfering with how the code of the mod applies changes in stats like when a mob is being attacked, and in these situations, the game cannot register input or interaction with the ingame world for a period of time depending on the specs of your PC. PCs and computers with higher specs usually experience shorter periods of these pauses. If the pause is too long, it results in your situation, where the player believes it necessary to use Task Manager or a similar application to kill the process that runs the game. Failing that, is the player does nothing, the excessive pause will result in the game simply CTDing. TheXFactor117 is currently working on a fix for this, but it may be some time before the update is pushed out.

Also something of note, since 1.7.10, JEI has automatic NEI intergration in its code. Hell, the mod was BUILT to support most of NEI's functions from the start. If you somehow found a way to port NEI to 1.12.2 and are running both at the same time, mod compatibility is DEFINITELY an issue, as the mods are separate from each other and run on differing codebases.

One more thing to note: in order to reduce this kind of lag and give your computer a chance to recover from the long pauses, you need to disable all your active resource packs, if any.

**Comment by TheXFactor117** [comment]
This is a known issue and has been fixed. Sorry about being MIA with some hotfix updates but I’m trying to push out a hotfix sometime this weekend which will fix all of these issues.

**Comment by lucalattanzio97** [comment]
it still doesnt work... aroud level 10, the world starts to freeze... i can freely go anywhere, but mobs are still and blocks dont give drops

**Comment by TheXFactor117** [comment]
Sorry for the long wait but it may or may not be fixed I'll have to look into it again.

**Comment by TheXFactor117** [comment]
Should be fixed in 0.6.2.0.
